# Définition du pipeline
# Il s'agit d'un pipeline simple qui se déclenche à chaque push sur la branche main de GitLab.
default:
  tags:
    - Usine_Logicielle
  timeout: 30 minutes
# Définition des étapes du pipeline
stages:
  - sync
# Définition des variables globales pour tous les jobs  
#============================

variables: 

  # Variables globales déclarées en dehors du yaml, définies automatiquement par Gitlab (Liste non exhaustive. Voir https://docs.gitlab.com/ee/ci/pipelines/index.html#prefill-variables-in-manual-pipelines) 
  #============================
  # non utilisées dans ce yaml

  # Variables globales déclarées en dehors du yaml, définies par l'UL au niveau de l’instance Gitlab 
  #============================
  # CNES_CERTIFICATE 
  
  # Variables globales déclarées en dehors du yaml, définies par l'UL, au niveau du groupe Gitlab dans le menu "Settings > CI/CD > Variables", et héritées par le projet : 
  #============================
  # Pour les images Docker sur Artifactory : 
  # DOCKER_AUTH_CONFIG 
  # Pour la connexion à Artifactory : 
  # ARTIFACTORY_HOST 
  # Pour les connexions par proxy : 
  # NO_PROXY 
  # PROXY_URL 
  # PROXY_USER
  # PROXY_PWD 
  # …

  # Variables globales déclarées en dehors du yaml, définies par l'UL, au niveau du projet Gitlab dans le menu "Settings > CI/CD > Variables" : 
  #============================

  # GITHUB_TOKEN
  # GITHUB_TOKEN_NAME
  # GITHUB_URL 

  # Variables globales déclarées dans le yaml :  
  #============================

  # url générique du serveur contenant les images docker
  ARTIFACTORY_URL: "${ARTIFACTORY_HOST}/publicremotes-docker"
  # Paramètres proxy
  HTTP_PROXY: http://${PROXY_USER}:${PROXY_PWD}@${PROXY_URL}
  HTTPS_PROXY: http://${PROXY_USER}:${PROXY_PWD}@${PROXY_URL}
  NO_PROXY: ${NO_PROXY}

# Définition de la tâche de synchronisation du dépôt GitLab vers le dépôt GitHub
sync:
  stage: sync
  # Définition de l'image Docker utilisée pour le pipeline. On préfère une image avec git déjà installé.
  image:
    name: ${ARTIFACTORY_URL}/alpine/git
    entrypoint: [""]

  before_script:
    # Ajout des certificats CNES pour permettre au runner de cloner le dépôt Gitlab.
    - cat ${CNES_CERTIFICATE} > /usr/local/share/ca-certificates/my-cert.crt
    # Mise à jour des certificats
    - update-ca-certificates
  script:
    # Clone du dépôt gitlab
    - git clone $CI_REPOSITORY_URL
    # On se positionne dans le dossier du dépôt cloné.
    - cd $(basename $CI_REPOSITORY_URL .git)
    # Ajoute le remote github avec les informations d'identification
    - git remote add gitlabsync https://${GITHUB_TOKEN_NAME}:${GITHUB_TOKEN}@${GITHUB_URL}/gitlabsync.git 
    # Pousse les modifications de la branche main de Gitlab vers la branche main de GitHub.
    - git push gitlabsync main:main
    # Declenchement du pipeline à partir de la branche main uniquement
#  only:
#    - main
  timeout: 20 minutes
