# Définition du pipeline
# Il s'agit d'un pipeline simple qui se déclenche à chaque push sur la branche main de GitLab.
default:
  tags:
    - Usine_Logicielle
# Définition des étapes du pipeline
stages:
  - sync
variables:  
  # url générique du serveur contenant les images docker
  ARTIFACTORY_URL: "${ARTIFACTORY_HOST}/publicremotes-docker"
  # Paramètres proxy
  HTTP_PROXY: http://${PROXY_USER}:${PROXY_PWD}@${PROXY_URL}
  HTTPS_PROXY: http://${PROXY_USER}:${PROXY_PWD}@${PROXY_URL}
  NO_PROXY: ${NO_PROXY}
# Définition de la tâche de synchronisation du dépôt GitLab vers le dépôt GitHub
sync:
  stage: sync
  # Définition de l'image Docker utilisée pour le pipeline. On préfère une image avec git déjà installé.
  image:
    name: ${ARTIFACTORY_URL}/alpine/git
    entrypoint: [""]

  before_script:
    # Ajout des certificats CNES pour permettre au runner de cloner le dépôt Gitlab.
    - cat ${CNES_CERTIFICATE} > /usr/local/share/ca-certificates/my-cert.crt
    # Mise à jour des certificats
    - update-ca-certificates
  script:
    # Clone du dépôt gitlab
    - git clone $CI_REPOSITORY_URL
    # On se positionne dans le dossier du dépôt cloné.
    - cd $(basename $CI_REPOSITORY_URL .git)
    # Ajoute le remote github avec les informations d'identification
    - git remote add gitlabsync https://${GITHUB_TOKEN_NAME}:${GITHUB_TOKEN}@${GITHUB_URL}/gitlabsync.git 
    # Pousse les modifications de la branche main de Gitlab vers la branche main de GitHub.
    - git push gitlabsync main:main
    # Déclenchement du pipeline à partir de la branche main uniquement
  only:
    - main
